apiVersion: v1
kind: Service
metadata:
  name: api-iris-service-production
spec:
  ports:
  - protocol: TCP
    port: 5050
    nodePort: 30007
  type: NodePort
  selector: 
    role: api-iris
    env: production